version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: pomodoro_db_dev
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: pomodoro_go
      MYSQL_USER: pomodorouser
      MYSQL_PASSWORD: ghty123iojk
    volumes:
      - db_data_dev:/var/lib/mysql
    ports:
      - "3307:3306"
    healthcheck:
      test:
        ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-prootpass"]
      timeout: 20s
      retries: 10
      interval: 10s
      start_period: 30s
    networks:
      - pomodoro-network

  redis:
    image: redis:7-alpine
    container_name: pomodoro_redis_dev
    ports:
      - "6379:6379"
    volumes:
      - redis_data_dev:/data
    networks:
      - pomodoro-network

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
      target: development
    container_name: pomodoro_backend_dev
    volumes:
      - ./server:/app
      - /app/tmp # Exclude tmp directory (CompileDaemon uses this)
    environment:
      - PORT=8000
      - DB=${DB_USER}:${DB_PASSWORD}@tcp(db:3306)/pomodoro_go?charset=utf8mb4&parseTime=True&loc=Local
      - SECRET=${SECRET}
      - REFRESH_SECRET=${REFRESH_SECRET}
      - FRONTEND_URL=${FRONTEND_URL}
      - REDIS_ADDR=redis:6379
      - REDIS_PASS=${REDIS_PASS}
      - EMAIL_PASS=${EMAIL_PASS}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - GITHUB_REDIRECT_URL=${GITHUB_REDIRECT_URL}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REDIRECT_URL=${GOOGLE_REDIRECT_URL}
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - pomodoro-network

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
      target: development
    container_name: pomodoro_frontend_dev
    volumes:
      - ./client:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NEXT_PUBLIC_LOCAL_STORAGE_KEY=widgetPosition
      - NEXT_PUBLIC_LOCAL_STORAGE_KEY_BG=wrksFeatures
      - NEXT_PUBLIC_LOCAL_STORAGE_KEY_MEDIA=savedPlaylist
      - NEXT_PUBLIC_LOCAL_STORAGE_KEY_OPACITY=widgetOpacity
      - NEXT_PUBLIC_START_PAUSE_AUDIO=https://rgovnbwjyfeqtiaucemw.supabase.co/storage/v1/object/public/audio_files//button.wav
      - NEXT_PUBLIC_RAIN_AUDIO=https://rgovnbwjyfeqtiaucemw.supabase.co/storage/v1/object/public/audio_files//rainSound.mp3
      - NEXT_PUBLIC_CLICK_AUDIO=https://rgovnbwjyfeqtiaucemw.supabase.co/storage/v1/object/public/audio_files//click.mp3
      - NEXT_PUBLIC_TWINKLE_AUDIO=https://rgovnbwjyfeqtiaucemw.supabase.co/storage/v1/object/public/audio_files//twinkle.mp3
      - NEXT_PUBLIC_ALARM_AUDIO=https://rgovnbwjyfeqtiaucemw.supabase.co/storage/v1/object/public/audio_files//alarm-digital.mp3
      - NEXT_PUBLIC_TOKYO_PREVIEW=https://rgovnbwjyfeqtiaucemw.supabase.co/storage/v1/object/public/imgs//tokyo.png
      - NEXT_PUBLIC_FOREST_PREVIEW=https://rgovnbwjyfeqtiaucemw.supabase.co/storage/v1/object/public/imgs//forest.png
      - NEXT_PUBLIC_SWISS_PREVIEW=https://rgovnbwjyfeqtiaucemw.supabase.co/storage/v1/object/public/imgs//swiss.png
      - NEXT_PUBLIC_SPACE_PREVIEW=https://rgovnbwjyfeqtiaucemw.supabase.co/storage/v1/object/public/imgs//space.png
      - NEXT_PUBLIC_TOKYO_SKY_PREVIEW=https://rgovnbwjyfeqtiaucemw.supabase.co/storage/v1/object/public/imgs//city.png
      - NEXT_PUBLIC_SHIBUYA_PREVIEW=https://rgovnbwjyfeqtiaucemw.supabase.co/storage/v1/object/public/imgs//Shibuya.png
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - pomodoro-network

volumes:
  db_data_dev:
  redis_data_dev:

networks:
  pomodoro-network:
    driver: bridge
